"""empty message

Revision ID: 0d99dd8bcc79
Revises: ccd26c1c3e39
Create Date: 2024-06-07 01:24:22.603247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d99dd8bcc79'
down_revision: Union[str, None] = 'ccd26c1c3e39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jokes', 'text',
               existing_type=sa.VARCHAR(length=280),
               type_=sa.String(length=3500),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jokes', 'text',
               existing_type=sa.String(length=3500),
               type_=sa.VARCHAR(length=280),
               existing_nullable=False)
    # ### end Alembic commands ###
