"""empty message

Revision ID: 5cd6bf474cc1
Revises: 72db030b58fe
Create Date: 2024-06-06 02:34:31.676065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cd6bf474cc1'
down_revision: Union[str, None] = '72db030b58fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jokes', sa.Column('creator_user_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jokes', 'creator_user_id')
    # ### end Alembic commands ###
