"""empty message

Revision ID: a76ca19938d8
Revises: 5cd6bf474cc1
Create Date: 2024-06-06 13:51:34.006762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a76ca19938d8'
down_revision: Union[str, None] = '5cd6bf474cc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jokes', sa.Column('accepted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jokes', 'accepted')
    # ### end Alembic commands ###
