"""empty message

Revision ID: c4b1d7868862
Revises: 0d99dd8bcc79
Create Date: 2024-06-07 18:12:31.908403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4b1d7868862'
down_revision: Union[str, None] = '0d99dd8bcc79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jokes', sa.Column('creator_nickname', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jokes', 'creator_nickname')
    # ### end Alembic commands ###
