"""empty message

Revision ID: e6b16df6fb16
Revises: cd8474d7f42b
Create Date: 2024-06-06 19:22:07.540468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6b16df6fb16'
down_revision: Union[str, None] = 'cd8474d7f42b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jokes', sa.Column('creator_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'jokes', 'users', ['creator_id'], ['user_id'])
    op.drop_column('jokes', 'creator_user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jokes', sa.Column('creator_user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'jokes', type_='foreignkey')
    op.drop_column('jokes', 'creator_id')
    # ### end Alembic commands ###
